PostgresHost: # Postgres地址
PostgresPort: # Postgres端口
PostgresUsername: # Postgres用户名
PostgresPassword: # Postgres密码
PostgresDatabase: # Postgres数据库

RedisHost: # Redis地址
RedisPort: # Redis端口
RedisPassword: # Redis密码

MinioAccessKey: # MinioAccessKey
MinioSecretKey: # MinioSecretKey

MiniProgramAppID: # 小程序AppID
MiniProgramAppSecret: # 小程序AppSecret

SMTPHost: # SMTP地址
SMTPPort: # SMTP端口
SMTPUsername: # SMTP用户名
SMTPPassword: # SMTP密码

TencentCloudSecretID: # 腾讯云SecretId
TencentCloudSecretKey: # 腾讯云SecretKey

LogPath: # 日志路径
DocsPath: # Swagger Base URL